In [1]:
!pip install h2o mlflow dagshub scikit-learn pandas matplotlib -q

In [ ]:
import h2o
from h2o.automl import H2OAutoML
import pandas as pd
import mlflow
import dagshub

In [ ]:
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "17.0.19" 2026-04-21; OpenJDK Runtime Environment (build 17.0.19+10-1-22.04.2-Ubuntu); OpenJDK 64-Bit Server VM (build 17.0.19+10-1-22.04.2-Ubuntu, mixed mode, sharing)
  Starting server from /usr/local/lib/python3.12/dist-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmpgjph_puz
  JVM stdout: /tmp/tmpgjph_puz/h2o_unknownUser_started_from_python.out
  JVM stderr: /tmp/tmpgjph_puz/h2o_unknownUser_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  -----------------------------------------------------------------------------------------
H2O_cluster_uptime:         04 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.11
H2O_cluster_version_age:    2 months and 16 days
H2O_cluster_name:           H2O_from_python_unknownUser_j9vyg4
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    3.168 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null, "colab_language_server": "/usr/colab/bin/language_service"}
H2O_internal_security:      False
Python_version:             3.12.13 final
--------------------------  -----------------------------------------------------------------------------------------

In [ ]:
data = {
    "study_hours": [1,2,3,4,5,6,7,8],
    "attendance": [50,55,60,70,75,85,90,95],
    "internal_marks": [35,40,45,60,70,75,85,90],
    "result": ["Fail","Fail","Fail","Pass","Pass","Pass","Pass","Pass"]
}

df = pd.DataFrame(data)

df.to_csv("dataset.csv", index=False)

print("Dataset created successfully")

df

Dataset created successfully

   study_hours  attendance  internal_marks result
0            1          50              35   Fail
1            2          55              40   Fail
2            3          60              45   Fail
3            4          70              60   Pass
4            5          75              70   Pass
5            6          85              75   Pass
6            7          90              85   Pass
7            8          95              90   Pass

In [ ]:
data = pd.read_csv("dataset.csv")

h2o_data = h2o.H2OFrame(data)

h2o_data

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

  study_hours    attendance    internal_marks  result
-------------  ------------  ----------------  --------
            1            50                35  Fail
            2            55                40  Fail
            3            60                45  Fail
            4            70                60  Pass
            5            75                70  Pass
            6            85                75  Pass
            7            90                85  Pass
            8            95                90  Pass
[8 rows x 4 columns]

In [ ]:
features = [
    "study_hours",
    "attendance",
    "internal_marks"
]

target = "result"

In [ ]:
train, test = h2o_data.split_frame(
    ratios=[0.8],
    seed=42
)

print("Training Data:")
print(train.shape)

print("Testing Data:")
print(test.shape)

Training Data:
(8, 4)
Testing Data:
(0, 4)

In [ ]:
from h2o.automl import H2OAutoML

automl = H2OAutoML(
    max_models=10,
    seed=42,
    max_runtime_secs=120
)

automl.train(
    x=features,
    y=target,
    training_frame=train
)

print("AutoML Training Completed")

AutoML progress: |████
03:12:54.585: _min_rows param, The dataset size is too small to split for min_rows=100.0: must have at least 200.0 (weighted) rows, but have only 8.0.

██
03:12:58.97: _min_rows param, The dataset size is too small to split for min_rows=10.0: must have at least 20.0 (weighted) rows, but have only 8.0.
03:12:58.98: _min_rows param, The dataset size is too small to split for min_rows=10.0: must have at least 20.0 (weighted) rows, but have only 8.0.
03:12:58.99: _min_rows param, The dataset size is too small to split for min_rows=10.0: must have at least 20.0 (weighted) rows, but have only 8.0.

██████████████████
03:13:26.961: StackedEnsemble_BestOfFamily_1_AutoML_1_20260808_31245 [StackedEnsemble best_of_family_xglm (built with AUTO metalearner, using top model from each algorithm type)] failed: java.lang.RuntimeException: water.exceptions.H2OIllegalArgumentException: Not enough data to create 5 random cross-validation splits. Either reduce nfolds, specify a larger dataset (or specify another random number seed, if applicable).
03:13:27.89: StackedEnsemble_AllModels_1_AutoML_1_20260808_31245 [StackedEnsemble all_xglm (built with AUTO metalearner, using all AutoML models)] failed: java.lang.RuntimeException: water.exceptions.H2OIllegalArgumentException: Not enough data to create 5 random cross-validation splits. Either reduce nfolds, specify a larger dataset (or specify another random number seed, if applicable).

███████████████████████████████████████| (done) 100%
AutoML Training Completed

In [ ]:
leaderboard = automl.leaderboard

leaderboard

model_id                                             auc    logloss     aucpr    mean_per_class_error       rmse         mse
----------------------------------------------  --------  ---------  --------  ----------------------  ---------  ----------
GBM_5_AutoML_1_20260808_31245                   1         0          1                            0    0          0
GBM_grid_1_AutoML_1_20260808_31245_model_1      1         0.0186413  1                            0    0.0488917  0.0023904
XRT_1_AutoML_1_20260808_31245                   1         0.0525998  1                            0    0.0969211  0.00939371
DRF_1_AutoML_1_20260808_31245                   1         0.0557859  1                            0    0.127279   0.0162
GLM_1_AutoML_1_20260808_31245                   1         0.106802   1                            0    0.169975   0.0288914
DeepLearning_1_AutoML_1_20260808_31245          0.866667  2.44841    0.93834                      0.1  0.611422   0.373837
XGBoost_1_AutoML_1_20260808_31245               0.5       0.693147   0.625                        0.5  0.5        0.25
XGBoost_2_AutoML_1_20260808_31245               0.5       0.693147   0.625                        0.5  0.5        0.25
XGBoost_3_AutoML_1_20260808_31245               0.5       0.693147   0.625                        0.5  0.5        0.25
XGBoost_grid_1_AutoML_1_20260808_31245_model_1  0.3       0.703898   0.527391                     0.5  0.504221   0.254239
[10 rows x 7 columns]

In [ ]:
best_model = automl.leader

best_model

Model Details
=============
H2OGradientBoostingEstimator : Gradient Boosting Machine
Model Key: GBM_5_AutoML_1_20260808_31245


Model Summary:
    number_of_trees    number_of_internal_trees    model_size_in_bytes    min_depth    max_depth    mean_depth    min_leaves    max_leaves    mean_leaves
--  -----------------  --------------------------  ---------------------  -----------  -----------  ------------  ------------  ------------  -------------
    467                467                         39557                  1            1            1             2             2             2

ModelMetricsBinomial: gbm
** Reported on train data. **

MSE: 0.0
RMSE: 0.0
LogLoss: 0.0
Mean Per-Class Error: 0.0
AUC: 1.0
AUCPR: 1.0
Gini: 1.0

Confusion Matrix (Act/Pred) for max f1 @ threshold = 1.0
       Fail    Pass    Error    Rate
-----  ------  ------  -------  ---------
Fail   3       0       0        (0.0/3.0)
Pass   0       5       0        (0.0/5.0)
Total  3       5       0        (0.0/8.0)

Maximum Metrics: Maximum metrics at their respective thresholds
metric                       threshold    value    idx
---------------------------  -----------  -------  -----
max f1                       1            1        0
max f2                       1            1        0
max f0point5                 1            1        0
max accuracy                 1            1        0
max precision                1            1        0
max recall                   1            1        0
max specificity              1            1        0
max absolute_mcc             1            1        0
max min_per_class_accuracy   1            1        0
max mean_per_class_accuracy  1            1        0
max tns                      1            3        0
max fns                      1            0        0
max fps                      1e-19        3        1
max tps                      1            5        0
max tnr                      1            1        0
max fnr                      1            0        0
max fpr                      1e-19        1        1
max tpr                      1            1        0

Gains/Lift Table: Avg response rate: 62.50 %, avg score: 62.50 %
group    cumulative_data_fraction    lower_threshold    lift    cumulative_lift    response_rate    score    cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain    cumulative_gain    kolmogorov_smirnov
-------  --------------------------  -----------------  ------  -----------------  ---------------  -------  --------------------------  ------------------  --------------  -------------------------  ------  -----------------  --------------------
1        0.625                       1                  1.6     1.6                1                1        1                           1                   1               1                          60      60                 1
2        0.625                       0.8                0       1.6                0                0        1                           1                   0               1                          -100    60                 1
3        0.625                       0.1                0       1.6                0                0        1                           1                   0               1                          -100    60                 1
4        1                           1e-19              0       1                  0                1e-19    0.625                       0.625               0               1                          -100    0                  0

ModelMetricsBinomial: gbm
** Reported on cross-validation data. **

MSE: 0.0
RMSE: 0.0
LogLoss: 0.0
Mean Per-Class Error: 0.0
AUC: 1.0
AUCPR: 1.0
Gini: 1.0

Confusion Matrix (Act/Pred) for max f1 @ threshold = 1.0
       Fail    Pass    Error    Rate
-----  ------  ------  -------  ---------
Fail   3       0       0        (0.0/3.0)
Pass   0       5       0        (0.0/5.0)
Total  3       5       0        (0.0/8.0)

Maximum Metrics: Maximum metrics at their respective thresholds
metric                       threshold    value    idx
---------------------------  -----------  -------  -----
max f1                       1            1        0
max f2                       1            1        0
max f0point5                 1            1        0
max accuracy                 1            1        0
max precision                1            1        0
max recall                   1            1        0
max specificity              1            1        0
max absolute_mcc             1            1        0
max min_per_class_accuracy   1            1        0
max mean_per_class_accuracy  1            1        0
max tns                      1            3        0
max fns                      1            0        0
max fps                      3.26572e-18  3        3
max tps                      1            5        0
max tnr                      1            1        0
max fnr                      1            0        0
max fpr                      3.26572e-18  1        3
max tpr                      1            1        0

Gains/Lift Table: Avg response rate: 62.50 %, avg score: 62.50 %
group    cumulative_data_fraction    lower_threshold    lift    cumulative_lift    response_rate    score    cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain    cumulative_gain    kolmogorov_smirnov
-------  --------------------------  -----------------  ------  -----------------  ---------------  -------  --------------------------  ------------------  --------------  -------------------------  ------  -----------------  --------------------
1        0.625                       1                  1.6     1.6                1                1        1                           1                   1               1                          60      60                 1
2        0.625                       0.8                0       1.6                0                0        1                           1                   0               1                          -100    60                 1
3        0.625                       0.1                0       1.6                0                0        1                           1                   0               1                          -100    60                 1
4        1                           0                  0       1                  0                0        0.625                       0.625               0               1                          -100    0                  0

Cross-Validation Metrics Summary:
                         mean    sd         cv_1_valid    cv_2_valid    cv_3_valid    cv_4_valid    cv_5_valid
-----------------------  ------  ---------  ------------  ------------  ------------  ------------  ------------
accuracy                 1.0     0.0        1.0           1.0           1.0           1.0           1.0
aic                      nan     0.0        nan           nan           nan           nan           nan
auc                      1.0     0.0        1.0           1.0           1.0           1.0           1.0
err                      0.0     0.0        0.0           0.0           0.0           0.0           0.0
err_count                0.0     0.0        0.0           0.0           0.0           0.0           0.0
f0point5                 1.0     0.0        1.0           1.0           1.0           1.0           1.0
f1                       1.0     0.0        1.0           1.0           1.0           1.0           1.0
f2                       1.0     0.0        1.0           1.0           1.0           1.0           1.0
lift_top_group           1.6     0.5477226  2.0           2.0           2.0           1.0           1.0
loglikelihood            nan     0.0        nan           nan           nan           nan           nan
---                      ---     ---        ---           ---           ---           ---           ---
mcc                      1.0     0.0        1.0           1.0           1.0           nan           nan
mean_per_class_accuracy  1.0     0.0        1.0           1.0           1.0           1.0           1.0
mean_per_class_error     0.0     0.0        0.0           0.0           0.0           0.0           0.0
mse                      0.0     0.0        0.0           0.0           0.0           0.0           0.0
pr_auc                   1.0     0.0        1.0           1.0           1.0           1.0           1.0
precision                1.0     0.0        1.0           1.0           1.0           1.0           1.0
r2                       1.0     0.0        1.0           1.0           1.0           nan           nan
recall                   1.0     0.0        1.0           1.0           1.0           1.0           1.0
rmse                     0.0     0.0        0.0           0.0           0.0           0.0           0.0
specificity              1.0     0.0        1.0           1.0           1.0           nan           nan
[22 rows x 8 columns]


Scoring History:
     timestamp            duration    number_of_trees    training_rmse          training_logloss      training_auc    training_pr_auc    training_lift    training_classification_error
---  -------------------  ----------  -----------------  ---------------------  --------------------  --------------  -----------------  ---------------  -------------------------------
     2026-08-08 03:13:12  11.560 sec  0.0                0.4841229182759271     0.6615632381579821    0.5             0.625              1.0              0.375
     2026-08-08 03:13:12  11.568 sec  5.0                0.28744098531349976    0.33179423348005704   1.0             1.0                1.6              0.0
     2026-08-08 03:13:12  11.573 sec  10.0               0.17281061705143097    0.1849078812159212    1.0             1.0                1.6              0.0
     2026-08-08 03:13:12  11.579 sec  15.0               0.10433948954340246    0.10722099396976364   1.0             1.0                1.6              0.0
     2026-08-08 03:13:12  11.585 sec  20.0               0.06312498456781018    0.0633989639438956    1.0             1.0                1.6              0.0
     2026-08-08 03:13:12  11.591 sec  25.0               0.038231183813121156   0.037886859196803555  1.0             1.0                1.6              0.0
     2026-08-08 03:13:12  11.597 sec  30.0               0.023168343944167575   0.022778172607918094  1.0             1.0                1.6              0.0
     2026-08-08 03:13:12  11.621 sec  35.0               0.014045061989749965   0.013743077471197568  1.0             1.0                1.6              0.0
     2026-08-08 03:13:13  11.628 sec  40.0               0.00851612387776561    0.008309223611846687  1.0             1.0                1.6              0.0
     2026-08-08 03:13:13  11.635 sec  45.0               0.0051643253470328165  0.005030166712740673  1.0             1.0                1.6              0.0
---  ---                  ---         ---                ---                    ---                   ---             ---                ---              ---
     2026-08-08 03:13:13  12.481 sec  425.0              0.0                    0.0                   1.0             1.0                1.6              0.0
     2026-08-08 03:13:13  12.491 sec  430.0              0.0                    0.0                   1.0             1.0                1.6              0.0
     2026-08-08 03:13:13  12.500 sec  435.0              0.0                    0.0                   1.0             1.0                1.6              0.0
     2026-08-08 03:13:13  12.508 sec  440.0              0.0                    0.0                   1.0             1.0                1.6              0.0
     2026-08-08 03:13:13  12.517 sec  445.0              0.0                    0.0                   1.0             1.0                1.6              0.0
     2026-08-08 03:13:13  12.527 sec  450.0              0.0                    0.0                   1.0             1.0                1.6              0.0
     2026-08-08 03:13:13  12.536 sec  455.0              0.0                    0.0                   1.0             1.0                1.6              0.0
     2026-08-08 03:13:13  12.544 sec  460.0              0.0                    0.0                   1.0             1.0                1.6              0.0
     2026-08-08 03:13:13  12.555 sec  465.0              0.0                    0.0                   1.0             1.0                1.6              0.0
     2026-08-08 03:13:13  12.561 sec  467.0              0.0                    0.0                   1.0             1.0                1.6              0.0
[95 rows x 10 columns]


Variable Importances:
variable        relative_importance    scaled_importance    percentage
--------------  ---------------------  -------------------  ------------
internal_marks  4.35537                1                    0.434352
study_hours     2.9362                 0.674155             0.292821
attendance      2.73571                0.628123             0.272827

[tips]
Use `model.explain()` to inspect the model.
--
Use `h2o.display.toggle_user_tips()` to switch on/off this section.

In [ ]:
import pandas as pd
import random

data = []

for i in range(100):

    study_hours = random.randint(1, 10)
    attendance = random.randint(50, 100)
    internal_marks = random.randint(35, 100)

    if (study_hours >= 5 and attendance >= 75 and internal_marks >= 60):
        result = "Pass"
    else:
        result = "Fail"

    data.append([
        study_hours,
        attendance,
        internal_marks,
        result
    ])

df = pd.DataFrame(
    data,
    columns=[
        "study_hours",
        "attendance",
        "internal_marks",
        "result"
    ]
)

df.to_csv("dataset.csv", index=False)

df.head()

   study_hours  attendance  internal_marks result
0            8          80              80   Pass
1           10          90              45   Fail
2            7          53              36   Fail
3            8          65              64   Fail
4            5          54              63   Fail

In [ ]:
data = pd.read_csv("dataset.csv")

h2o_data = h2o.H2OFrame(data)

h2o_data["result"] = h2o_data["result"].asfactor()

h2o_data.head()

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

  study_hours    attendance    internal_marks  result
-------------  ------------  ----------------  --------
            8            80                80  Pass
           10            90                45  Fail
            7            53                36  Fail
            8            65                64  Fail
            5            54                63  Fail
            9            97                50  Fail
            9            93                36  Fail
            6            64                90  Fail
            2            56                79  Fail
            4            83                55  Fail
[10 rows x 4 columns]

In [ ]:
train, test = h2o_data.split_frame(
    ratios=[0.8],
    seed=42
)

print("Train:", train.shape)
print("Test:", test.shape)

Train: (82, 4)
Test: (18, 4)

In [ ]:
from h2o.automl import H2OAutoML

features = [
    "study_hours",
    "attendance",
    "internal_marks"
]

target = "result"

automl = H2OAutoML(
    max_models=10,
    seed=42,
    max_runtime_secs=120
)

automl.train(
    x=features,
    y=target,
    training_frame=train
)

print("AutoML Training Completed")

AutoML progress: |███
03:18:19.118: _min_rows param, The dataset size is too small to split for min_rows=100.0: must have at least 200.0 (weighted) rows, but have only 82.0.

████████████████████████████████████████████████████████████| (done) 100%
AutoML Training Completed

In [ ]:
leaderboard = automl.leaderboard

leaderboard

model_id                                                     auc    logloss     aucpr    mean_per_class_error      rmse        mse
------------------------------------------------------  --------  ---------  --------  ----------------------  --------  ---------
GBM_3_AutoML_3_20260808_31812                           0.995475  0.0752824  0.986318               0.0294118  0.129132  0.016675
StackedEnsemble_BestOfFamily_1_AutoML_3_20260808_31812  0.99457   0.0819797  0.984311               0.0294118  0.149357  0.0223076
GBM_2_AutoML_3_20260808_31812                           0.993665  0.0768138  0.982475               0.0294118  0.131564  0.0173091
StackedEnsemble_AllModels_1_AutoML_3_20260808_31812     0.99095   0.103782   0.970454               0.0447964  0.180118  0.0324425
GBM_5_AutoML_3_20260808_31812                           0.990045  0.131334   0.970406               0.0588235  0.200106  0.0400423
XRT_1_AutoML_3_20260808_31812                           0.990045  0.155228   0.976468               0.0294118  0.190631  0.0363403
GBM_4_AutoML_3_20260808_31812                           0.990045  0.0866646  0.976468               0.0294118  0.133229  0.01775
DRF_1_AutoML_3_20260808_31812                           0.968778  0.143608   0.96025                0.0294118  0.169388  0.0286924
XGBoost_3_AutoML_3_20260808_31812                       0.909502  0.288468   0.87987                0.0895928  0.27779   0.0771675
GLM_1_AutoML_3_20260808_31812                           0.895928  0.320425   0.695591               0.193213   0.318706  0.101573
[12 rows x 7 columns]

In [ ]:
best_model = automl.leader

print("Best Model:")
print(best_model)

Best Model:
Model Details
=============
H2OGradientBoostingEstimator : Gradient Boosting Machine
Model Key: GBM_3_AutoML_3_20260808_31812


Model Summary:
    number_of_trees    number_of_internal_trees    model_size_in_bytes    min_depth    max_depth    mean_depth    min_leaves    max_leaves    mean_leaves
--  -----------------  --------------------------  ---------------------  -----------  -----------  ------------  ------------  ------------  -------------
    556                556                         66910                  2            5            2.9982        3             6             4.86511

ModelMetricsBinomial: gbm
** Reported on train data. **

MSE: 7.131651731510343e-19
RMSE: 8.444910734584672e-10
LogLoss: 3.1383184433756677e-10
Mean Per-Class Error: 0.0
AUC: 1.0
AUCPR: 1.0
Gini: 1.0

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.9999999999482374
       Fail    Pass    Error    Rate
-----  ------  ------  -------  -----------
Fail   65      0       0        (0.0/65.0)
Pass   16      1       0.9412   (16.0/17.0)
Total  81      1       0.1951   (16.0/82.0)

Maximum Metrics: Maximum metrics at their respective thresholds
metric                       threshold    value     idx
---------------------------  -----------  --------  -----
max f1                       1            1         15
max f2                       1            1         15
max f0point5                 1            1         15
max accuracy                 1            1         15
max precision                1            1         0
max recall                   1            1         15
max specificity              1            1         0
max absolute_mcc             1            1         15
max min_per_class_accuracy   1            1         15
max mean_per_class_accuracy  1            1         15
max tns                      1            65        0
max fns                      1            16        0
max fps                      1e-19        65        60
max tps                      1            17        15
max tnr                      1            1         0
max fnr                      1            0.941176  0
max fpr                      1e-19        1         60
max tpr                      1            1         15

Gains/Lift Table: Avg response rate: 20.73 %, avg score: 20.73 %
group    cumulative_data_fraction    lower_threshold    lift     cumulative_lift    response_rate    score        cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain     cumulative_gain    kolmogorov_smirnov
-------  --------------------------  -----------------  -------  -----------------  ---------------  -----------  --------------------------  ------------------  --------------  -------------------------  -------  -----------------  --------------------
1        0.0121951                   1                  4.82353  4.82353            1                1            1                           1                   0.0588235       0.0588235                  382.353  382.353            0.0588235
2        0.0243902                   1                  4.82353  4.82353            1                1            1                           1                   0.0588235       0.117647                   382.353  382.353            0.117647
3        0.0487805                   1                  4.82353  4.82353            1                1            1                           1                   0.117647        0.235294                   382.353  382.353            0.235294
4        0.0487805                   1                  0        4.82353            0                0            1                           1                   0               0.235294                   -100     382.353            0.235294
5        0.0609756                   1                  4.82353  4.82353            1                1            1                           1                   0.0588235       0.294118                   382.353  382.353            0.294118
6        0.109756                    1                  4.82353  4.82353            1                1            1                           1                   0.235294        0.529412                   382.353  382.353            0.529412
7        0.158537                    1                  4.82353  4.82353            1                1            1                           1                   0.235294        0.764706                   382.353  382.353            0.764706
8        0.207317                    0.8                4.82353  4.82353            1                1            1                           1                   0.235294        1                          382.353  382.353            1
9        0.304878                    2.64859e-10        0        3.28               0                1.13061e-09  0.68                        0.68                0               1                          -100     228                0.876923
10       0.402439                    1.21636e-10        0        2.48485            0                1.767e-10    0.515152                    0.515152            0               1                          -100     148.485            0.753846
11       0.5                         7.72958e-11        0        2                  0                9.25385e-11  0.414634                    0.414634            0               1                          -100     100                0.630769
12       0.597561                    2.02174e-11        0        1.67347            0                4.23953e-11  0.346939                    0.346939            0               1                          -100     67.3469            0.507692
13       0.695122                    2.54678e-12        0        1.4386             0                1.04341e-11  0.298246                    0.298246            0               1                          -100     43.8596            0.384615
14       1                           1e-19              0        1                  0                1.10171e-13  0.207317                    0.207317            0               1                          -100     0                  0

ModelMetricsBinomial: gbm
** Reported on cross-validation data. **

MSE: 0.01667497705018271
RMSE: 0.12913162683937157
LogLoss: 0.07528239252677484
Mean Per-Class Error: 0.029411764705882353
AUC: 0.995475113122172
AUCPR: 0.9863176424603256
Gini: 0.9909502262443439

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.7297056458321146
       Fail    Pass    Error    Rate
-----  ------  ------  -------  ----------
Fail   65      0       0        (0.0/65.0)
Pass   1       16      0.0588   (1.0/17.0)
Total  66      16      0.0122   (1.0/82.0)

Maximum Metrics: Maximum metrics at their respective thresholds
metric                       threshold    value     idx
---------------------------  -----------  --------  -----
max f1                       0.729706     0.969697  9
max f2                       0.729706     0.952381  9
max f0point5                 0.729706     0.987654  9
max accuracy                 0.729706     0.987805  9
max precision                1            1         0
max recall                   0.0190205    1         15
max specificity              1            1         0
max absolute_mcc             0.729706     0.962765  9
max min_per_class_accuracy   0.729706     0.941176  9
max mean_per_class_accuracy  0.729706     0.970588  9
max tns                      1            65        0
max fns                      1            10        0
max fps                      1e-19        65        62
max tps                      0.0190205    17        15
max tnr                      1            1         0
max fnr                      1            0.588235  0
max fpr                      1e-19        1         62
max tpr                      0.0190205    1         15

Gains/Lift Table: Avg response rate: 20.73 %, avg score: 18.88 %
group    cumulative_data_fraction    lower_threshold    lift      cumulative_lift    response_rate    score        cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain      cumulative_gain    kolmogorov_smirnov
-------  --------------------------  -----------------  --------  -----------------  ---------------  -----------  --------------------------  ------------------  --------------  -------------------------  --------  -----------------  --------------------
1        0.0853659                   1                  4.82353   4.82353            1                1            1                           1                   0.411765        0.411765                   382.353   382.353            0.411765
2        0.109756                    0.9988             4.82353   4.82353            1                0.999135     1                           0.999808            0.117647        0.529412                   382.353   382.353            0.529412
3        0.158537                    0.750033           4.82353   4.82353            1                0.885788     1                           0.964725            0.235294        0.764706                   382.353   382.353            0.764706
4        0.207317                    0.201077           3.61765   4.53979            0.75             0.603433     0.941176                    0.879715            0.176471        0.941176                   261.765   353.979            0.925792
5        0.304878                    0.0146983          0.602941  3.28               0.125            0.0587468    0.68                        0.617005            0.0588235       1                          -39.7059  228                0.876923
6        0.402439                    0.000997428        0         2.48485            0                0.00681685   0.515152                    0.469081            0               1                          -100      148.485            0.753846
7        1                           0                  0         1                  0                3.07224e-05  0.207317                    0.188795            0               1                          -100      0                  0

Cross-Validation Metrics Summary:
                         mean         sd           cv_1_valid    cv_2_valid     cv_3_valid     cv_4_valid     cv_5_valid
-----------------------  -----------  -----------  ------------  -------------  -------------  -------------  -------------
accuracy                 0.9882353    0.026306681  0.9411765     1.0            1.0            1.0            1.0
aic                      nan          0.0          nan           nan            nan            nan            nan
auc                      0.9787879    0.047431745  0.8939394     1.0            1.0            1.0            1.0
err                      0.011764706  0.026306681  0.05882353    0.0            0.0            0.0            0.0
err_count                0.2          0.4472136    1.0           0.0            0.0            0.0            0.0
f0point5                 0.99230766   0.017200522  0.96153843    1.0            1.0            1.0            1.0
f1                       0.9818182    0.04065578   0.90909094    1.0            1.0            1.0            1.0
f2                       0.9724138    0.061684635  0.86206895    1.0            1.0            1.0            1.0
lift_top_group           6.766667     5.283097     2.8333333     5.6666665      16.0           4.0            5.3333335
loglikelihood            nan          0.0          nan           nan            nan            nan            nan
---                      ---          ---          ---           ---            ---            ---            ---
mcc                      0.9748015    0.056345616  0.87400734    1.0            1.0            1.0            1.0
mean_per_class_accuracy  0.98333335   0.0372678    0.9166667     1.0            1.0            1.0            1.0
mean_per_class_error     0.016666668  0.0372678    0.083333336   0.0            0.0            0.0            0.0
mse                      0.014778601  0.033022456  0.07385095    2.3854342e-31  4.7091325e-19  4.2049734e-05  2.4212993e-19
pr_auc                   0.98132336   0.041762218  0.90661687    1.0            1.0            1.0            1.0
precision                1.0          0.0          1.0           1.0            1.0            1.0            1.0
r2                       0.9352796    0.14459385   0.67662233    1.0            1.0            0.9997757      1.0
recall                   0.96666664   0.0745356    0.8333333     1.0            1.0            1.0            1.0
rmse                     0.05564798   0.1208403    0.2717553     4.8840904e-16  6.862312e-10   0.0064845765   4.92067e-10
specificity              1.0          0.0          1.0           1.0            1.0            1.0            1.0
[22 rows x 8 columns]


Scoring History:
     timestamp            duration    number_of_trees    training_rmse           training_logloss        training_auc    training_pr_auc      training_lift       training_classification_error
---  -------------------  ----------  -----------------  ----------------------  ----------------------  --------------  -------------------  ------------------  -------------------------------
     2026-08-08 03:18:43  6.659 sec   0.0                0.40538463752669923     0.510380230286545       0.5             0.20731707317073167  1.0                 0.7926829268292683
     2026-08-08 03:18:43  6.666 sec   5.0                0.32819376044294785     0.35881862824933164     1.0             1.0                  0.0                 0.0
     2026-08-08 03:18:43  6.671 sec   10.0               0.2604113234530007      0.25927312710635964     1.0             1.0                  4.8235294117647065  0.0
     2026-08-08 03:18:43  6.675 sec   15.0               0.2281981817717517      0.21625206900982882     1.0             1.0                  4.8235294117647065  0.0
     2026-08-08 03:18:43  6.680 sec   20.0               0.19332780113348233     0.17371406434280637     1.0             1.0                  4.8235294117647065  0.0
     2026-08-08 03:18:43  6.685 sec   25.0               0.15145033372497727     0.1309702113808188      1.0             1.0                  4.8235294117647065  0.0
     2026-08-08 03:18:43  6.690 sec   30.0               0.13107017507149746     0.10850450990992833     1.0             1.0                  4.8235294117647065  0.0
     2026-08-08 03:18:43  6.694 sec   35.0               0.10728983468390337     0.08741412470257336     1.0             1.0                  4.8235294117647065  0.0
     2026-08-08 03:18:43  6.699 sec   40.0               0.09326262009506943     0.07340019606653417     1.0             1.0                  4.8235294117647065  0.0
     2026-08-08 03:18:43  6.704 sec   45.0               0.07904735004952577     0.05815195176522515     1.0             1.0                  4.8235294117647065  0.0
---  ---                  ---         ---                ---                     ---                     ---             ---                  ---                 ---
     2026-08-08 03:18:44  7.387 sec   515.0              3.829481197397434e-09   1.4973441327158345e-09  1.0             1.0                  4.8235294117647065  0.0
     2026-08-08 03:18:44  7.396 sec   520.0              3.3468957105227668e-09  1.2988757226097742e-09  1.0             1.0                  4.8235294117647065  0.0
     2026-08-08 03:18:44  7.404 sec   525.0              2.927517415315572e-09   1.123255375115246e-09   1.0             1.0                  4.8235294117647065  0.0
     2026-08-08 03:18:44  7.412 sec   530.0              2.4606009440362377e-09  9.252456202772535e-10   1.0             1.0                  4.8235294117647065  0.0
     2026-08-08 03:18:44  7.421 sec   535.0              2.017983977988153e-09   7.505701351820121e-10   1.0             1.0                  4.8235294117647065  0.0
     2026-08-08 03:18:44  7.429 sec   540.0              1.6335359210311803e-09  5.84173495465156e-10    1.0             1.0                  4.8235294117647065  0.0
     2026-08-08 03:18:44  7.438 sec   545.0              1.4412137631004808e-09  5.202930955544744e-10   1.0             1.0                  4.8235294117647065  0.0
     2026-08-08 03:18:44  7.446 sec   550.0              1.1754838941075572e-09  4.2826073921597466e-10  1.0             1.0                  4.8235294117647065  0.0
     2026-08-08 03:18:44  7.454 sec   555.0              9.240388840104998e-10   3.3720890215006257e-10  1.0             1.0                  4.8235294117647065  0.0
     2026-08-08 03:18:44  7.461 sec   556.0              8.444910734584672e-10   3.1383184433756677e-10  1.0             1.0                  4.8235294117647065  0.0
[113 rows x 10 columns]


Variable Importances:
variable        relative_importance    scaled_importance    percentage
--------------  ---------------------  -------------------  ------------
attendance      24.558                 1                    0.469654
internal_marks  20.0059                0.814639             0.382598
study_hours     7.72565                0.314588             0.147748

In [ ]:
performance = best_model.model_performance(test)

print("Model evaluation completed")

Model evaluation completed

In [ ]:
accuracy = performance.accuracy([0.5])[0][1]
precision = performance.precision([0.5])[0][1]
recall = performance.recall([0.5])[0][1]
f1_score = performance.F1([0.5])[0][1]

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1_score)

Could not find exact threshold 0.5; using closest threshold found 1.473579339980245e-08.
Could not find exact threshold 0.5; using closest threshold found 1.473579339980245e-08.
Could not find exact threshold 0.5; using closest threshold found 1.473579339980245e-08.
Could not find exact threshold 0.5; using closest threshold found 1.473579339980245e-08.
Accuracy : 0.9444444444444444
Precision: 0.0
Recall   : nan
F1 Score : nan

In [ ]:
print("========== AutoML Results ==========")
print("Best Model :", best_model.model_id)
print("Accuracy   :", accuracy)
print("Precision  :", precision)
print("Recall     :", recall)
print("F1 Score   :", f1_score)

========== AutoML Results ==========
Best Model : GBM_3_AutoML_3_20260808_31812
Accuracy   : 0.9444444444444444
Precision  : 0.0
Recall     : nan
F1 Score   : nan

In [ ]:
results = pd.DataFrame({
    "Metric": [
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score"
    ],
    "Value": [
        accuracy,
        precision,
        recall,
        f1_score
    ]
})

results.to_csv("automl_results.csv", index=False)

results

      Metric     Value
0   Accuracy  0.944444
1  Precision  0.000000
2     Recall       NaN
3   F1 Score       NaN

In [ ]:
model_path = h2o.save_model(
    model=best_model,
    path="automl_model",
    force=True
)

print("Model saved at:", model_path)

Model saved at: /content/automl_model/GBM_3_AutoML_3_20260808_31812

In [ ]:
!ls -lh

total 20K
drwxr-xr-x 2 root root 4.0K Aug  8 03:23 automl_model
-rw-r--r-- 1 root root   73 Aug  8 03:23 automl_results.csv
-rw-r--r-- 1 root root 1.4K Aug  8 03:14 dataset.csv
drwx------ 5 root root 4.0K Aug  8 03:07 drive
drwxr-xr-x 1 root root 4.0K Jun  4 13:32 sample_data

In [ ]:
sample = h2o.H2OFrame({
    "study_hours": [7],
    "attendance": [85],
    "internal_marks": [80]
})

prediction = best_model.predict(sample)

prediction

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
gbm prediction progress: |███████████████████████████████████████████████████████| (done) 100%

predict           Fail    Pass
---------  -----------  ------
Pass       2.16203e-10       1
[1 row x 3 columns]

In [ ]:
import dagshub
import mlflow

dagshub.init(
    repo_owner="2420080026",
    repo_name="mlops-shared-repo",
    mlflow=True
)

mlflow.set_experiment("H2O_AutoML_Experiment")

print("DagsHub and MLflow configured successfully")

                                       ❗❗❗ AUTHORIZATION REQUIRED ❗❗❗

Output()

Open the following link in your browser to authorize the client:
https://dagshub.com/login/oauth/authorize?state=355aeb7e-bb14-4f27-8ac8-f58a9bdfabaa&client_id=32b60ba385aa7cecf24046d8195a71c07dd345d9657977863b52e7748e0f0f28&middleman_request_id=969b92d6f2455b85e57502c58347c3dca2086a8195e027f50072c794528792a5

Accessing as 2420080026

Initialized MLflow to track repo "2420080026/mlops-shared-repo"

Repository 2420080026/mlops-shared-repo initialized!

2026/08/08 03:26:00 INFO mlflow.tracking.fluent: Experiment with name 'H2O_AutoML_Experiment' does not exist. Creating a new experiment.

DagsHub and MLflow configured successfully

In [ ]:
with mlflow.start_run():

    # Parameters
    mlflow.log_param(
        "algorithm",
        "H2O AutoML"
    )

    mlflow.log_param(
        "max_models",
        10
    )

    mlflow.log_param(
        "dataset",
        "student_performance"
    )

    # Metrics
    mlflow.log_metric(
        "accuracy",
        accuracy
    )

    mlflow.log_metric(
        "precision",
        precision
    )

    mlflow.log_metric(
        "recall",
        recall
    )

    mlflow.log_metric(
        "f1_score",
        f1_score
    )

print("MLflow logging completed")

🏃 View run bouncy-stork-210 at: https://dagshub.com/2420080026/mlops-shared-repo.mlflow/#/experiments/1/runs/178cb56f69924e92b3d904b1643a3d81
🧪 View experiment at: https://dagshub.com/2420080026/mlops-shared-repo.mlflow/#/experiments/1
MLflow logging completed

In [ ]:
model_path = h2o.save_model(
    model=best_model,
    path="/content/automl_model",
    force=True
)

print("Model saved at:", model_path)

Model saved at: /content/automl_model/GBM_3_AutoML_3_20260808_31812

In [ ]:
with mlflow.start_run():

    mlflow.log_artifact(
        model_path,
        artifact_path="model"
    )

print("Model artifact logged")

🏃 View run invincible-sow-128 at: https://dagshub.com/2420080026/mlops-shared-repo.mlflow/#/experiments/1/runs/0ec4f078faff433f99d331eec394e40b
🧪 View experiment at: https://dagshub.com/2420080026/mlops-shared-repo.mlflow/#/experiments/1
Model artifact logged

In [ ]:
new_data = h2o.H2OFrame(
    {
        "study_hours": [8],
        "attendance": [95],
        "internal_marks": [90]
    }
)

prediction = best_model.predict(new_data)

prediction

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
gbm prediction progress: |███████████████████████████████████████████████████████| (done) 100%

predict           Fail    Pass
---------  -----------  ------
Pass       2.65589e-10       1
[1 row x 3 columns]

In [ ]:
results = pd.DataFrame(
    {
        "Model": ["H2O AutoML Best Model"],
        "Accuracy": [accuracy],
        "Precision": [precision],
        "Recall": [recall],
        "F1 Score": [f1_score]
    }
)

results.to_csv(
    "automl_results.csv",
    index=False
)

results

                   Model  Accuracy  Precision  Recall  F1 Score
0  H2O AutoML Best Model  0.944444        0.0     NaN       NaN

In [ ]:
!ls -la

total 32
drwxr-xr-x 1 root root 4096 Aug  8 03:23 .
drwxr-xr-x 1 root root 4096 Aug  8 02:53 ..
drwxr-xr-x 2 root root 4096 Aug  8 03:23 automl_model
-rw-r--r-- 1 root root   88 Aug  8 03:28 automl_results.csv
drwxr-xr-x 4 root root 4096 Jun  4 13:32 .config
-rw-r--r-- 1 root root 1356 Aug  8 03:14 dataset.csv
drwx------ 5 root root 4096 Aug  8 03:07 drive
drwxr-xr-x 1 root root 4096 Jun  4 13:32 sample_data

In [3]:
from getpass import getpass

token = getpass("Enter DagsHub Token:")

Enter DagsHub Token:··········
Enter DagsHub Token:··········

In [6]:
!git clone https://2420080026:{token}@dagshub.com/2420080026/mlops-shared-repo.git

Cloning into 'mlops-shared-repo'...
warning: You appear to have cloned an empty repository.

In [7]:
%cd /content/mlops-shared-repo

/content/mlops-shared-repo

In [8]:
!ls -la

total 12
drwxr-xr-x 3 root root 4096 Aug  8 03:47 .
drwxr-xr-x 1 root root 4096 Aug  8 03:47 ..
drwxr-xr-x 7 root root 4096 Aug  8 03:47 .git

In [9]:
!cp /content/dataset.csv .
!cp /content/automl_results.csv .

In [10]:
!ls -la

total 20
drwxr-xr-x 3 root root 4096 Aug  8 03:48 .
drwxr-xr-x 1 root root 4096 Aug  8 03:47 ..
-rw-r--r-- 1 root root   88 Aug  8 03:48 automl_results.csv
-rw-r--r-- 1 root root 1356 Aug  8 03:48 dataset.csv
drwxr-xr-x 7 root root 4096 Aug  8 03:47 .git

In [11]:
!git config user.name "VK-1805"
!git config user.email "2420080026@klh.edu.in"

In [12]:
!git add dataset.csv automl_results.csv

In [13]:
!git status

On branch main

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   automl_results.csv
	new file:   dataset.csv

In [14]:
!git commit -m "Completed Skill Session 4 - H2O AutoML"

[main (root-commit) d8f20f3] Completed Skill Session 4 - H2O AutoML
 2 files changed, 103 insertions(+)
 create mode 100644 automl_results.csv
 create mode 100644 dataset.csv

In [15]:
!git push origin main

Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 2 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 855 bytes | 855.00 KiB/s, done.
Total 4 (delta 0), reused 0 (delta 0), pack-reused 0
To https://dagshub.com/2420080026/mlops-shared-repo.git
 * [new branch]      main -> main